spring:
  application:
    name: orderservice
  cloud:
    config:
      profile: local
  config:
    import: "configserver:${configurl}"
  kafka:
    bootstrap-server : localhost:9092
    template:
      default-topic: orderTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


configurl: http://localhost:8079